# RAFAEL: GENERATED BY GEMINI

$PROJECT_NAME = "paint_app"

# --- Configuration for Rust Installation ---
$RUSTUP_INIT_URL = "https://win.rustup.rs/x86_64"
$RUSTUP_INIT_PATH = "$env:TEMP\rustup-init.exe"
$RUST_BIN_PATH = "$env:USERPROFILE\.cargo\bin"

# Stop the script immediately if any command fails
$ErrorActionPreference = "Stop"

Write-Host "--- Starting Rust Project Build for $PROJECT_NAME ---" -ForegroundColor Cyan

# 1. Install Rust (This is silent and only executes the install if Rust is not found)
Write-Host "1. Checking/Installing Rust environment..." -ForegroundColor Yellow

try {
    # Download the installer
    Invoke-WebRequest -Uri $RUSTUP_INIT_URL -OutFile $RUSTUP_INIT_PATH
    
    # Execute the installer silently (-y) using default, stable toolchain
    # This automatically adds cargo to the system PATH for future sessions.
    & $RUSTUP_INIT_PATH -y --default-toolchain stable
    
    # Add cargo bin to the current PowerShell session's PATH for immediate use
    $env:PATH += ";$RUST_BIN_PATH"
    
    Write-Host "   Rust environment is ready." -ForegroundColor Green
} catch {
    Write-Error "FATAL: Failed to install or configure Rust. Check internet connection or permissions."
    exit 1
} finally {
    # Clean up the downloaded installer file
    Remove-Item $RUSTUP_INIT_PATH -Force -ErrorAction SilentlyContinue
}

# 2. Run Optimized Release Build
Write-Host "2. Running optimized release compilation: 'cargo build --release'..." -ForegroundColor Yellow

try {
    # The --release flag optimizes the executable for performance.
    & cargo build --release
    Write-Host "--- BUILD SUCCESSFUL ---" -ForegroundColor Green

    # 3. Report Executable Location
    $EXE_PATH = ".\target\release\$($PROJECT_NAME).exe"
    
    Write-Host "The final executable is ready and located at:" -ForegroundColor Cyan
    Write-Host $EXE_PATH -ForegroundColor White
    Write-Host "Run it using: & '$EXE_PATH'" -ForegroundColor Green

} catch {
    Write-Error "--- BUILD FAILED ---"
    Write-Error "An error occurred during compilation. Please review the output above for errors."
    exit 1
}

Write-Host "--- Script Finished ---"
